# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               write_desk
tagline:             'a place where word meets string'
description:         'language, thought, and world.'
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Mike Wong
  url:               https://twitter.com/saviormike
  email:             saviormike@gmail.com

# Custom vars
version:             1.0.0
